# Generated by Django 6.0 on 2025-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_attempts_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
