# Generated by Django 6.0 on 2025-12-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('primary_email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_signedin', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=255)),
                ('updated_at', models.CharField(max_length=255)),
                ('last_active_at', models.CharField(max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('profile_image', models.URLField()),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('verification_attempts_remaining', models.IntegerField(default=0)),
                ('first_time_user', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
