# Generated by Django 6.0 on 2025-12-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TenantUser',
        ),
    ]
