# Generated by Django 6.0 on 2025-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_tenantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(default='07', max_length=13),
        ),
    ]
