# Generated by Django 6.0 on 2025-12-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='phone_number',
        ),
    ]
