# Generated by Django 6.0 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_adminuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='user_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
